name: ${project.name}
version: ${build.number}
description: ${project.description}
author: ['md_5', 'ammar2']
website: ${project.url}

main: ${main.class}

commands:
  janus:
    usage: /janus
