name: ${project.name}
version: ${build.number}
description: ${project.description}
authors: ['md_5', 'ammar2']
website: ${project.url}

main: ${main.class}

commands:
  janus:
    usage: /janus
    permission: janus.command
permissions:
  janus.command:
    description: "Allows user to use the /janus command"
  janus.command.create:
    description: "Allows user to use the /janus create, /janus cancel and /janus confirm commands (for portal creation)"
  janus.command.reload:
    description: "Allows user to use the /janus reload command"
  janus.command.remove:
    description: "Allows user to use the /janus remove command"
  janus.portal.use:
    default: true
    description: "Allows user to use janus portals"

